@startuml

title __SEMESTRAL_WORK's Class Diagram__\n

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.BuildConfig {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.BuildConfig {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.BuildConfig {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.BuildConfig {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.Note {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.Note {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.NoteAdapter {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.NoteAdapter {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.Utility {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.Utility {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    class com.example.taskmanager_prma_r21207.Utility {
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    namespace test {
      class com.example.taskmanager_prma_r21207.test.BuildConfig {
      }
    }
  }
  

  namespace com.example.taskmanager_prma_r21207 {
    namespace test {
      class com.example.taskmanager_prma_r21207.test.BuildConfig {
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
